---
title: "Tidy Data"
author: "Jun"
date: "9/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```



## Wide to Long
```{r echo=TRUE}
pulse_data = haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat")%>%
janitor::clean_names()

#pulse_tidy_data = 
#  pivot_longer(
#    pulse_data, 
#    bdi_score_bl:bdi_score_12m,
#    names_to = "visit", 
 #   values_to = "bdi")
#remove "bdi_score_"
pulse_tidy_data = 
  pivot_longer(
    pulse_data, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")%>%
  mutate(
    visit = recode(visit,"bl" = "00m")
  )

#the code below will import, tidy, and transform the PULSE dataset into a usable format
#pulse_data = 
#  haven::read_sas("./data_import_examples/public_pulse_data.sas7bdat") %>%
#  janitor::clean_names() %>%
#  pivot_longer(
#    bdi_score_bl:bdi_score_12m,
#    names_to = "visit", 
#    names_prefix = "bdi_score_",
#    values_to = "bdi") %>%
#  select(id, visit, everything()) %>%
#  mutate(
#    visit = replace(visit, visit == "bl", "00m"),
#    visit = factor(visit, levels = str_c(c("00", "01", "06", "12"), "m"))) %>%
#  arrange(id, visit)
```



## separate in litters

```{r}
#litters_data = read_csv("./data_import_examples/FAS_litters.csv")%>%
#  janitor::clean_names()%>%
# separate(col = group, into = c("dose", "day_of_tx"),3)
#we can also do more things
litters_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  separate(group, into = c("dose", "day_of_tx"), sep = 3) %>%
  mutate(
    dose = str_to_lower(dose),
    wt_gain = gd18_weight - gd0_weight) %>%
  arrange(litter_number)
```

## 
```{r}
litters_data %>% 
  select(litter_number, ends_with("weight")) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") %>% 
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))
```


## go untidy....

```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")

```

## binding rows

```{r}
fellowship_ring = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data_import_examples/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")


lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  pivot_longer(
    female:male,
    names_to = "sex", 
    values_to = "words") %>%
  mutate(race = str_to_lower(race)) %>% 
  select(movie, everything()) 
```

## join datasets

```{r}
pup_data = 
  read_csv("./data_import_examples/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = 
  read_csv("./data_import_examples/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group))

fas_data = 
  left_join(pup_data, litter_data, by = "litter_number")
# could join by multiple variables
# we can also join by different variables
```






















