---
title: "importdata"
output: html_document
---

```{r pre}
library(tidyverse)
## ── Attaching packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.2.1 ──
## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
## ✔ tidyr   1.0.0     ✔ stringr 1.4.0
## ✔ readr   1.3.1     ✔ forcats 0.4.0
## ── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()


```

## R Markdown



```{r import}
litters_data = read.csv(file = "./data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```
```{r learning}
pups_data = read.csv(file = "./data_import_examples/FAS_pups.csv")
pups_data_new = read.csv(file = "/Users/junyin/Desktop/data science/data_import/data_import_examples/FAS_pups.csv")
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
